Compiler-options.sh terminé
Ajout de options-scripts utilisés par le fichier principal compiler-options.sh
Tout n'est pas encore 100% implémenté. Dépendant de ce qui a été fait ou pas

diff --git a/src/test/script/options-scripts/option-b b/src/test/script/options-scripts/option-b
--- a/src/test/script/options-scripts/option-b
+++ b/src/test/script/options-scripts/option-b
@@ -18,9 +18,22 @@ decac -b > ./src/test/script/options-scripts/option-b.tmp
 
 if cat ./src/test/script/options-scripts/option-b.tmp | grep -q "."
 then
-    echo -e "$GREENBOLD Test passed: $GREEN Option -b successfully implemented\n"
+    echo -e "${GREENBOLD}Test passed:$GREEN decac -b prints the banner"
 else 
-    echo -e "$REDBOLD Test failed: $RED Option -b not implemented\n"
+    echo -e "${REDBOLD}Test failed:$RED Option -b not implemented"
+    if [[ $1 == "--maven" ]];
+    then
+        exit 1
+    fi
+fi
+
+decac -b -v > ./src/test/script/options-scripts/option-b.tmp 2> ./src/test/script/options-scripts/option-b.tmp
+
+if [ "$?" -ne 0 ]
+then
+    echo -e "${GREENBOLD}Test passed:$GREEN decac -b with another option returns an error\n"
+else 
+    echo -e "${REDBOLD}Test failed:$RED decac -b not implemented correctly\n"
     if [[ $1 == "--maven" ]];
     then
         exit 1
diff --git a/src/test/script/options-scripts/option-p b/src/test/script/options-scripts/option-p
--- a/src/test/script/options-scripts/option-p
+++ b/src/test/script/options-scripts/option-p
@@ -20,8 +20,6 @@ PATH=./src/test/script/launchers:"$PATH"
 
 files=$(find ./src/test/deca/codegen/valid -maxdepth 1 -name "*.deca")
 
-NB_VALID_TESTS=0
-VALID_PASSED=0
 
 echo -e "${BWHITE}============================= -p option =============================\n"
 
@@ -37,10 +35,9 @@ do
     # check if passed
     if [ "$diff" = "" ] 
     then
-        ((VALID_PASSED = VALID_PASSED + 1))
-        echo -e "$GREENBOLD Test passed ($VALID_PASSED/$NB_VALID_TESTS): $GREEN$test"
+        echo -e "${GREENBOLD}Test passed: $NOCOLOR${test/.\/src\/test\/deca\//} ${GREEN}parsed and decompiled gives the same result after execution"
     else
-        echo -e "$REDBOLD Test failed ($VALID_PASSED/$NB_VALID_TESTS): $RED$test"
+        echo -e "${REDBOLD}Test failed: $NOCOLOR${test/.\/src\/test\/deca\//} ${RED}decompiled version does not return the same result after execution"
         if [[ $1 == "--maven" ]];
         then
             exit 1
@@ -48,19 +45,17 @@ do
     fi
 done
 
-VALID_PASSED_PERCENTAGE=`echo "$VALID_PASSED / $NB_VALID_TESTS * 100" | bc -l`
+decac -p -v > ./src/test/script/options-scripts/option-p.tmp 2> ./src/test/script/options-scripts/option-p.tmp
 
-TEMP=`echo "$VALID_PASSED_PERCENTAGE > 0.5" | bc -l`
-
-if ((TEMP));
+if [ "$?" -ne 0 ]
 then
-    echo -e "\n${GREEN} Valid test passed: "
-    printf %2.0f $VALID_PASSED_PERCENTAGE
-    echo "%"
-else
-    echo -e "\n${RED} Valid test passed: "
-    printf %2.0f $VALID_PASSED_PERCENTAGE
-    echo "%"
+    echo -e "${GREENBOLD}Test passed:$GREEN decac -p -v returns an error"
+else 
+    echo -e "${REDBOLD}Test failed:$RED decac -p not implemented correctly"
+    if [[ $1 == "--maven" ]];
+    then
+        exit 1
+    fi
 fi
 
 # Cleaning process
@@ -68,3 +63,4 @@ fi
 rm -r ./src/test/deca/codegen/valid/*_p.deca;
 rm -r ./src/test/deca/codegen/valid/*.res;
 rm -r ./src/test/deca/codegen/valid/*.ass;
+rm ./src/test/script/options-scripts/option-p.tmp
diff --git a/src/test/script/options-scripts/option-v b/src/test/script/options-scripts/option-v
--- a/src/test/script/options-scripts/option-v
+++ b/src/test/script/options-scripts/option-v
@@ -8,10 +8,6 @@ GREEN='\033[0;32m'
 NOCOLOR='\033[0m'
 BWHITE='\033[1;37m'
 
-# Stat var
-NB_VALID_TESTS=0
-VALID_PASSED=0
-
 # On se place dans le répertoire du projet (quel que soit le
 # répertoire d'où est lancé le script) :
 cd "$(dirname "$0")"/../../../../ || exit 1
@@ -24,18 +20,16 @@ files=$(find ./src/test/deca/context/valid -maxdepth 1 -name "*.deca")
 
 for test in $files
 do
-    ((NB_VALID_TESTS = NB_VALID_TESTS + 1))
     decac -v "$test" > "${test%.deca}".lis 2>&1
     if cat "${test%.deca}".lis | grep -q "."
     then
-        echo -e "${REDBOLD}Test failed ($VALID_PASSED/$NB_VALID_TESTS): ${RED}$test${NOCOLOR}"
+        echo -e "${REDBOLD}Test failed: $NOCOLOR${test/.\/src\/test\/deca/}${RED} returns an error even though the test is valid"
         if [[ $1 == "--maven" ]];
         then
             exit 1
         fi
     else
-        ((VALID_PASSED = VALID_PASSED + 1))
-        echo -e "${GREENBOLD}Test passed ($VALID_PASSED/$NB_VALID_TESTS): ${GREEN}$test${NOCOLOR}"
+        echo -e "${GREENBOLD}Test passed: $NOCOLOR${test/.\/src\/test\/deca\//} ${GREEN}returns nothing"
     fi
 done
 
@@ -43,14 +37,12 @@ files=$(find ./src/test/deca/context/invalid -maxdepth 1 -name "*.deca")
 
 for test in $files
 do
-    ((NB_VALID_TESTS = NB_VALID_TESTS + 1))
     decac -v "$test" > "${test%.deca}".lis 2>&1
     if cat "${test%.deca}".lis | grep -q "$test:*:*"
     then
-        ((VALID_PASSED = VALID_PASSED + 1))
-        echo -e "${GREENBOLD}Test passed ($VALID_PASSED/$NB_VALID_TESTS): ${GREEN}$test${NOCOLOR}"
+        echo -e "${GREENBOLD}Test passed: $NOCOLOR${test/.\/src\/test\/deca\//}${GREEN} returns a correct error"
     else
-        echo -e "${REDBOLD}Test failed ($VALID_PASSED/$NB_VALID_TESTS): ${RED}$test${NOCOLOR}"
+        echo -e "${REDBOLD}Test failed: $NOCOLOR${test/.\/src\/test\/deca\//}${RED} does not return a correct error even though the test in invalid"
         if [[ $1 == "--maven" ]];
         then
             exit 1
@@ -58,18 +50,18 @@ do
     fi
 done
 
-VALID_PASSED_PERCENTAGE=`echo "$VALID_PASSED / $NB_VALID_TESTS * 100" | bc -l`
-TEMP=`echo "$VALID_PASSED_PERCENTAGE > 0.5" | bc -l`
+decac -v -p > ./src/test/script/options-scripts/option-v.tmp 2> ./src/test/script/options-scripts/option-v.tmp
 
-if ((TEMP));
+if [ "$?" -ne 0 ]
 then
-    echo -e "\n${GREEN} Valid test passed: "
-    printf %2.0f $VALID_PASSED_PERCENTAGE
-    echo "%"
-else
-    echo -e "\n${RED} Valid test passed: "
-    printf %2.0f $VALID_PASSED_PERCENTAGE
-    echo "%"
+    echo -e "${GREENBOLD}Test passed:$GREEN decac -v -p returns an error"
+else 
+    echo -e "${REDBOLD}Test failed:$RED decac -v not implemented correctly"
+    if [[ $1 == "--maven" ]];
+    then
+        exit 1
+    fi
 fi
 
 rm -r ./src/test/deca/context/*/*.lis
+rm ./src/test/script/options-scripts/option-v.tmp
