Ajout des tests de compilation avec -p et -v

diff --git a/src/test/script/options-scripts/option-v b/src/test/script/options-scripts/option-v
--- a/src/test/script/options-scripts/option-v
+++ b/src/test/script/options-scripts/option-v
@@ -10,25 +10,23 @@ BWHITE='\033[1;37m'
 
 # Stat var
 NB_VALID_TESTS=0
-NB_INVALID_TESTS=0
 VALID_PASSED=0
-INVALID_PASSED=0
 
 # On se place dans le répertoire du projet (quel que soit le
 # répertoire d'où est lancé le script) :
-cd "$(dirname "$0")"/../../../ || exit 1
+cd "$(dirname "$0")"/../../../../ || exit 1
 
 PATH=./src/test/script/launchers:"$PATH"
 
-echo -e "${BWHITE} \n============================= Context valid tests =============================\n"
+echo -e "${BWHITE}\n============================= -v option =============================\n"
 
 files=$(find ./src/test/deca/context/valid -maxdepth 1 -name "*.deca")
 
 for test in $files
 do
     ((NB_VALID_TESTS = NB_VALID_TESTS + 1))
-    test_context "$test" > "${test%.deca}".lis 2>&1
-    if cat "${test%.deca}".lis | grep -q "${test}\|Exception in thread"
+    decac -v "$test" > "${test%.deca}".lis 2>&1
+    if cat "${test%.deca}".lis | grep -q "."
     then
         echo -e "${REDBOLD}Test failed ($VALID_PASSED/$NB_VALID_TESTS): ${RED}$test${NOCOLOR}"
         if [[ $1 == "--maven" ]];
@@ -41,20 +39,18 @@ do
     fi
 done
 
-echo -e "${BWHITE} \n============================= Context invalid tests =============================\n"
-
 files=$(find ./src/test/deca/context/invalid -maxdepth 1 -name "*.deca")
 
 for test in $files
 do
-    ((NB_INVALID_TESTS = NB_INVALID_TESTS + 1))
-    test_context "$test" > "${test%.deca}".lis 2>&1
+    ((NB_VALID_TESTS = NB_VALID_TESTS + 1))
+    decac -v "$test" > "${test%.deca}".lis 2>&1
     if cat "${test%.deca}".lis | grep -q "$test:*:*"
     then
-        ((INVALID_PASSED = INVALID_PASSED + 1))
-        echo -e "${GREENBOLD}Test passed ($INVALID_PASSED/$NB_INVALID_TESTS): ${GREEN}$test${NOCOLOR}"
+        ((VALID_PASSED = VALID_PASSED + 1))
+        echo -e "${GREENBOLD}Test passed ($VALID_PASSED/$NB_VALID_TESTS): ${GREEN}$test${NOCOLOR}"
     else
-        echo -e "${REDBOLD}Test failed ($INVALID_PASSED/$NB_INVALID_TESTS): ${RED}$test${NOCOLOR}"
+        echo -e "${REDBOLD}Test failed ($VALID_PASSED/$NB_VALID_TESTS): ${RED}$test${NOCOLOR}"
         if [[ $1 == "--maven" ]];
         then
             exit 1
@@ -63,8 +59,6 @@ do
 done
 
 VALID_PASSED_PERCENTAGE=`echo "$VALID_PASSED / $NB_VALID_TESTS * 100" | bc -l`
-INVALID_PASSED_PERCENTAGE=`echo "$INVALID_PASSED / $NB_INVALID_TESTS * 100" | bc -l`
-
 TEMP=`echo "$VALID_PASSED_PERCENTAGE > 0.5" | bc -l`
 
 if ((TEMP));
@@ -78,14 +72,4 @@ else
     echo "%"
 fi
 
-TEMP=`echo "$INVALID_PASSED_PERCENTAGE > 0.5" | bc -l`
-if ((TEMP));
-then
-    echo -e "\n${GREEN} Invalid test passed: "
-    printf %2.0f $INVALID_PASSED_PERCENTAGE
-    echo -e "%\n"
-else
-    echo -e "\n${RED} Invalid test passed: "
-    printf %2.0f $INVALID_PASSED_PERCENTAGE
-    echo -e "%\n"
-fi
+rm -r ./src/test/deca/context/*/*.lis
